[theme.variables]

wallpaper = "jade-theme-pic-4.jpg"
# wallpaper-engine-wp-id = "0"

font-family = "JetBrainsMono Nerd Font"
font-size = "10"

qt_theme = "breeze"
rounding = "1"
gaps = "4"

# primary
foreground = "#c1c497ff"
background = "#111c18ed"
foreground_alt = "#589a5fff"
background_alt = "#23372bff"
text = "#d7c995ff"
cursor = "#589a5fff"
accent = "#efff9dff"
accent_inactive = "#59595950"

# normal colors
palette_black = "#09100cff"
palette_red = "#5c2527ff"
palette_green = "#38543bff"
palette_yellow = "#acb165ff"
palette_blue = "#354063ff"
palette_magenta = "#4b3367ff"
palette_cyan = "#509489ff"
palette_white = "#c4c3b3ff"

# bright colors
palette_black_bright = "#070b09ff"
palette_red_bright = "#af2b2fff"
palette_green_bright = "#66a86eff"
palette_yellow_bright = "#d8e069ff"
palette_blue_bright = "#4e62a3ff"
palette_magenta_bright = "#7a42baff"
palette_cyan_bright = "#66cfbeff"
palette_white_bright = "#f3f3f0ff"