##################
#### PROGRAMS ####
##################

# See https://wiki.hypr.land/Configuring/Keywords/
# Set programs that you use

### HYPRLAND MANAGED SETUP ###

# $terminal = ghostty
# $fileManager = dolphin
# $appMenu = rofi -show drun
# $browser = firefox
# $discord = equibop
# $codeEditor = code
# $notes = obsidian
# $steam = steam
# $top = ghostty -e btop
# $musicPlayer = spotify

# $screenshot = hyprshot -m region
# $colorPicker = hyprpicker -a
# $toggleDiscordMute = equibop --toggle-mic
# $toggleDiscordDeafen = equibop --toggle-deafen
# $volumeUp = ~/.config/scripts/vol-up
# $volumeDown = ~/.config/scripts/vol-down
# $brightnessUp = ~/.config/scripts/brightness-up
# $brightnessDown = ~/.config/scripts/brightness-down
# $toggleVolume = ~/.config/scripts/vol-mute
# $toggleMic = ~/.config/scripts/mic-mute
# $toggleDisplay = ~/.config/scripts/toggle-display
# $switchTheme = ~/.config/scripts/rofi-theme-selector.sh


### UWSM MANAGED SETUP ###

$uwsm = uwsm app --   # Launch with UWSM

$terminal = $uwsm ghostty
# $terminal = $uwsm ghostty -e tmux
$fileManager = $uwsm dolphin
$appMenu = $uwsm rofi -show drun -run-command "uwsm app -- {cmd}"
$browser = $uwsm firefox
$discord = $uwsm equibop
$codeEditor = $uwsm code
$notes = $uwsm obsidian
$steam = $uwsm steam
$top = $uwsm ghostty -e btop
$musicPlayer = $uwsm spotify

$lockscreen = $uwsm hyprlock
$screenshot = $uwsm hyprshot -m region
$colorPicker = $uwsm hyprpicker -a
$toggleDiscordMute = $uwsm equibop --toggle-mic
$toggleDiscordDeafen = $uwsm equibop --toggle-deafen
$volumeUp = $uwsm ~/.config/scripts/vol-up
$volumeDown = $uwsm ~/.config/scripts/vol-down
$brightnessUp = $uwsm ~/.config/scripts/brightness-up
$brightnessDown = $uwsm ~/.config/scripts/brightness-down
$toggleVolume = $uwsm ~/.config/scripts/vol-mute
$toggleMic = $uwsm ~/.config/scripts/mic-mute
$toggleDisplay = $uwsm ~/.config/scripts/toggle-display
$switchTheme = $uwsm ~/.config/scripts/rofi-theme-selector.sh


##################
### AUTOSTARTS ###
##################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# exec-once = systemctl --user start hyprpolkitagent
# exec-once = waybar
# exec-once = hyprpaper
# exec-once = protonvpn-app
# exec-once = equibop