#!/bin/bash

wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
mute_status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o 'MUTED')
vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}')

if [ "$mute_status" = "MUTED" ]; then
    notify-send --replace-id=9991 -u low -i ~/.config/themes/icons/vol-muted.svg "Volume: Muted"
else
    notify-send --replace-id=9991 -h int:value:"$vol" -u low -i ~/.config/themes/icons/vol.svg "Volume: ${vol}%"
fi
